name: 00 USA BackEnd Nestjs

on:
  workflow_call: # 允许被其他工作流调用
    inputs:
      environment:
        required: true
        type: string
      app_name:
        required: true
        type: string
    secrets:
      DEPLOY_TOKEN:
        required: true

env:
  PROJECT_NAME: nestjs001

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.CICD_TOKEN }}

      - name: Deploy application
        run: |
          echo "Deploying ${{ inputs.app_name }} to ${{ inputs.environment }}"
          echo "Using token: ${{ secrets.DEPLOY_TOKEN }}"
          echo "Using token CICD: ${{ secrets.CICD_TOKEN }}"
