name: SLK Deploy BE

on:
  workflow_call: # 允许被其他工作流调用
    inputs:
      environment:
        required: true
        type: string
      app_name:
        required: true
        type: string
    secrets:
      CICD_TOKEN:
        required: true # 必须传递
      token:
        required: false # 可选传递（如果不需要可删除）
      DEPLOY_TOKEN: # 您之前传递的另一个secret
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy application
        run: |
          echo "Deploying ${{ inputs.app_name }} to ${{ inputs.environment }}"
          echo "Using token: ${{ secrets.DEPLOY_TOKEN }}"
          echo "Using token CICD: ${{ secrets.CICD_TOKEN }}"
